### ISSUE TITLE
(ios)App closed when click upload button twice.

### ISSUE THREAD

**Issue by kode-soar** [Rodiii/flutter_firebase_picture_uploader#10]
First of all, thank you for making a good package.

We are testing it to use it, but there is no problem with Android, but there is a phenomenon that the app is forced to shut down when clicking the second button on iOS.

It happens regardless of whether you actually uploaded the photo or not.

I am attaching

https://user-images.githubusercontent.com/46374669/102568353-a81d7e80-4126-11eb-89a9-d5eb089d5f85.mov

 file.

Please check.

Thank you.

**Comment by kode-soar** [comment]
Console Msg is below.

Restarted application in 621ms.
Lost connection to device.
Exited (sigterm)

**Comment by Rodiii** [comment]
Hi @kode-soar, Thanks for testing firebase_picture_uploader.

Indeed, I've seen this issue before and tried to fix it. This seems to be an issue within the image_picker library https://github.com/flutter/flutter/issues/70751

For me, this issue just happens in iOS simulator and not on real devices. Could you please check this?

I will keep this issue open until fixed by image_picker

**Comment by kode-soar** [comment]
I confirmed that it is working properly on the real device.

Thank you for your quick reply. :D

I hope this part is corrected quickly.

Thank you.
